baseURL = 'https://d2atxiswdqq4o3.cloudfront.net' # 'https://example.org/'
languageCode = 'ja'    #'en-us'
title = 'syulog Works' #'My New Hugo Site'
theme = "nagoya"
defaultContentLanguage = 'ja'
hasCJKLanguage = true   # 日本語・中国語・韓国語の処理改善
[taxonomies]
  category = "categories"
  tag = "tags"
  archive = "archives"
  search = "search"
[params]
  customCSS = ["css/custom-color.css"]
  headerImage = "images/top.jpeg"  # 例：static/images/top.jpeg に配置

